### ISSUE TITLE
Task ID: 3.4 Project Testing Black Box

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#55] opened 2023-11-07 09:18 UTC
Task Title: Black Box Testing Execution
ID: 3.4

1. Description: Conduct comprehensive black-box testing on the software project to validate functional requirements. This involves testing the software from an external perspective, without looking at the internal code structure, to ensure it meets specified input-output behavior.

2. Goal: To verify that all user-facing functionality behaves as expected under various conditions and to identify any discrepancies or defects in the requirements as implemented.

3. Success Criteria:
Completion of test cases that cover all user stories and functional requirements.
Documentation of test results, including any failures or anomalies.
Resolution of all critical and major issues identified during testing.
Acceptance of the testing report by the QA lead and project stakeholders.

4. Allocated Time: 2 weeks

5. Start: 1/11/23, End: 6/11/23

6. Owner: Khai

7. Priority: Medium

**Comment by KhairinNor** [comment] 2023-11-25 14:44
Describe work done in detail: Use Case 1 was used for BlackBox Testing. Identify the causes and effects of every possible scenarios. A decision table was then created for the causes and effects. The test case scenarios were done based on the (reduced) table. 
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: All the test cases have been verify and validated through every scenario and aligns with the figma
Start date of work done: 1th Nov 2023
End date of work done: 6th Nov 2023

**Closed as completed by KhairinNor** 2023-11-25 14:44 UTC
Labels: documentation
