### ISSUE TITLE
Task ID: 3.3 Project Prototype

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#54] opened 2023-11-07 09:14 UTC
Task Title: Project Prototype Development
ID: 3.3

1. Description: Develop a functional prototype of the software project that demonstrates the core features and functionalities as outlined in the initial design phase. The prototype should be written in a combination of real and pseudo-code to simulate the intended behavior of the system and highlight key interactions between components.

2. Goal: To create a working model that can be used to validate the design choices, gather feedback from stakeholders, and provide a tangible basis for further development phases. 

3. Success Criteria: Prototype should include the implementation of major functions and user flows.Code should be well-commented, with pseudo-code used where appropriate to represent incomplete logic or future development.
The prototype should be demonstrable and able to execute basic tasks as intended.
Feedback from the tech lead and project stakeholders based on the prototype's functionality

4. Allocated Time: 2 weeks

5.Start: 31/10/23, End: 9/11/23

6. Owner: Afiq

 7. Priority: High

**Comment by ahhhfiq** [comment] 2023-11-25 14:13
Describe work done in detail: Created a functional prototype that demonstrates the core features and functionalities as outlined.
Work committed to branch: NA
Does work affect deadline: No
Success criteria or completion: Prototype should include the implementation of major functions and user flows.Code should be well-commented, with pseudo-code used where appropriate to represent incomplete logic or future development.
The prototype should be demonstrable and able to execute basic tasks as intended.
Feedback from the tech lead and project stakeholders based on the prototype's functionality
Start date of work done: 7th Nov 2023
End date of work done: 19th Nov 2023

**Closed as completed** 2023-11-25 14:42 UTC
Labels: documentation
